### ISSUE TITLE
URL of Real Usage Example

### ISSUE THREAD

**Issue by Theorycrafting** [maxswa/osrs-json-hiscores#1]
It would be fantastic if there was an example URL of a deployed app using this JSON.
Perhaps a simple `vanilla codesandbox` and in the javascript file using `osrs-json-hiscores` and console logging that JSON response would be fantastic!

You have it very well documented, but when I went to use it, I was having troubles with getting errors. I think with CORS which I would normally prefix any endpoint with `https://cors-anywhere.herokuapp.com/`

If you want to talk about this otherwise, we could on disc or in game 👍
Rsn: `Bag`

**Comment by maxswa** [comment]
I apologize for the late response. The issue is that Jagex unfortunately doesn't provide an `Access-Control-Allow-Headers` header in their responses. This means that CORS will block all browser requests to their hiscores API. In order to get around this, `osrs-json-hiscores` should be installed on the server side and exposed to the front end via a simple API. Here is an example of this in use: https://codesandbox.io/s/osrs-json-hiscores-demo-qz656  
  
The front end app would just need to make a request with this pattern: `https://qz656.sse.codesandbox.io/stats/{rsn}`  
Obviously replacing the base codesandbox URL with the servers address.

**Comment by maxswa** [comment]
A disclaimer has now been added to the README
