### ISSUE TITLE
Option to disable calls to player table page when fetching stats

### ISSUE THREAD

**Issue by evanw555** [maxswa/osrs-json-hiscores#62]
## Background

Following up on my last issue (https://github.com/maxswa/osrs-json-hiscores/issues/60), it looks like my application is still failing to fetch player display names correctly, but this time it's due to the fact that I'm being rate-limited by the hiscores service. I confirmed this by testing usage of `getRSNFormat` directly on the network where I'm running my application (failure) vs testing usage on a different home network (success).

My application queries the hiscores using this library once every 3 seconds, and I read in [this Reddit comment](https://www.reddit.com/r/2007scape/comments/57ah3w/comment/d8qjlls/?utm_source=share&utm_medium=web2x&context=3) that the hiscores service has a rate limit of 15/minute, but I read somewhere else that this doesn't include the "lite API" (i.e. CSV API). This would explain why my application succeeds in querying the lite API 20 times per minute, but fails to resolve display names.

I need to reduce the amount of calls to the non-lite hiscores site so my application can successfully fetch display names on a less frequent basis. I can reduce the refresh interval of my application, but what would help the most would be to disable the player table request for most of the `getStats` calls.

## Feature Request

Add an option to `getStats` that disables the display name hiscores request.

What are your thoughts?

**Comment by maxswa** [comment]
`getStats` is a very overkill function that makes up to 5 network requests, and if I had to go back and re-write this library I may have omitted it altogether.

Does your app rely on the information that `getStats` provides that `getStatsByGamemode` does not? If not, I would suggest using `getStatsByGamemode` instead since it will be much more performant and you will be able to avoid the rate limiting much more easily.

That being said, I do agree that it would make sense to allow for options in `getStats` that can restrict which requests are made. I can start on this at some point soon, plus there are some other code refactors I've been meaning to get to.

**Comment by evanw555** [comment]
@maxswa Hmmmm this is an interesting recommendation. My application tracks normal players in addition to others such as ironman players. I was under the impression initially that you must use the ironman URL for ironman players, but it appears it succeeds, but with the ranks adjusted to be relative to all players vs ironman players. My application only counts levels/kills and XP (not ranks), so this may be viable.

Let me try this out, I'll let you know if it unblocks me.

**Comment by maxswa** [comment]
This feature was added in `osrs-json-hiscores@2.12.1`

You can use it like this:
```ts
const stats = await getStats(rsn, { shouldGetFormattedRsn: false });
```

I also added another option for limiting game mode fetches:
```ts
// Only fetch stats for "ironman" (aside from the required fetch of "main" stats)
const stats = await getStats(rsn, { otherGamemodes: ['ironman'] });
```
