### ISSUE TITLE
Can't find player when there is no total level on hs

### ISSUE THREAD

**Issue by geertjanvdenbosch** [maxswa/osrs-json-hiscores#7]
The wrapper is unable to find a player if the players' total level is not displayed on the highscores, eventhough other stats are shown on the highscores.

**Comment by maxswa** [comment]
I have been able to reproduce this and I'm currently investigating a solution.

**Comment by maxswa** [comment]
So the reason this was happening is pretty interesting actually. Jagex only tracks ranks up to 2,000,000 players. This means that if your total xp is less than the rank 2,000,000 player your rank will be `-1`
The way that I find a player's formatted display name is by looking them up on the rank table, but if they are unranked this is impossible. So inside of `getStats` it was failing because `getRSNFormat` was failing since it couldn't find the player on the rank table.

**Comment by maxswa** [comment]
Apologies for the delay, but the package has been published as [version `2.1.0`](https://www.npmjs.com/package/osrs-json-hiscores) as of today.
